#!/usr/bin/env python3
from __future__ import annotations
import argparse, base64, json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
PUB = ROOT / 'output' / 'published'
DEFAULT_OUTPUT = ROOT / 'promo_lab.html'

def load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise SystemExit(f'ไม่พบ {path}\nกรุณารัน: python place_enrichment_loop.py')
    data = json.loads(path.read_text(encoding='utf-8'))
    if not isinstance(data, dict):
        raise SystemExit(f'ไฟล์ {path} ไม่ใช่ JSON object')
    return data

def load_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        raise SystemExit(f'ไม่พบ {path}\nกรุณารัน: python place_enrichment_loop.py')
    rows=[]
    with path.open(encoding='utf-8') as f:
        for n,line in enumerate(f,1):
            if not line.strip(): continue
            try: x=json.loads(line)
            except json.JSONDecodeError as e: raise SystemExit(f'JSONL ผิดรูปแบบ {path}:{n}: {e}')
            if isinstance(x,dict): rows.append(x)
    return rows

def b64(x: Any) -> str:
    raw=json.dumps(x,ensure_ascii=False,separators=(',',':')).encode('utf-8')
    return base64.b64encode(raw).decode('ascii')

def build_html(manifest:dict, offers:list[dict], places:list[dict], index:dict)->str:
    payload=b64({'manifest':manifest,'offers':offers,'places':places,'index':index})
    return f'''<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light"><title>Promo Intelligence Lab</title>
<style>
:root{{--bg:#f2f7fb;--card:#fff;--ink:#10263d;--muted:#6a7b8e;--line:#dbe7ef;--blue:#1769c2;--cyan:#009bb7;--teal:#087f78;--good:#087b55;--warn:#a46a00;--bad:#b54141;--soft:#eaf5fb;--shadow:0 8px 24px rgba(16,38,61,.08)}}
*{{box-sizing:border-box}} body{{margin:0;background:linear-gradient(180deg,#eaf6fb 0,#f7fafc 260px,#f2f7fb 100%);font-family:system-ui,-apple-system,"Noto Sans Thai","Segoe UI",sans-serif;color:var(--ink)}} button,input,select{{font:inherit}} button{{cursor:pointer}} a{{color:var(--blue)}}
.shell{{max-width:1180px;margin:auto;padding:0 12px 48px}} .hero{{margin:0 -12px;padding:20px 16px 18px;background:linear-gradient(125deg,#124d94,#087bb5 55%,#088879);color:#fff;box-shadow:var(--shadow)}} .top{{display:flex;align-items:center;gap:11px}} .logo{{width:44px;height:44px;border-radius:14px;background:rgba(255,255,255,.18);display:grid;place-items:center;font-size:24px}} h1{{font-size:22px;margin:0}} .sub{{opacity:.9;font-size:13px;margin-top:2px}} .testbadge{{margin-left:auto;background:#fff;color:#9a4c00;border-radius:999px;padding:6px 10px;font-weight:800;font-size:12px}}
.notice{{margin-top:14px;padding:10px 12px;border-radius:12px;background:rgba(255,255,255,.13);font-size:12px;line-height:1.5}} .stats{{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:14px 0}} .stat{{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:11px;box-shadow:var(--shadow)}} .stat b{{display:block;font-size:20px}} .stat span{{font-size:11px;color:var(--muted)}}
.tabs{{display:flex;gap:8px;overflow:auto;padding:2px 0 12px;position:sticky;top:0;background:rgba(242,247,251,.96);z-index:5}} .tab{{border:1px solid var(--line);background:#fff;border-radius:999px;padding:9px 13px;color:var(--ink);white-space:nowrap}} .tab.active{{background:var(--blue);border-color:var(--blue);color:#fff}} .panel{{display:none}} .panel.active{{display:block}}
.controls{{background:#fff;border:1px solid var(--line);border-radius:16px;padding:12px;box-shadow:var(--shadow);margin-bottom:12px}} .grid2{{display:grid;grid-template-columns:2fr repeat(4,1fr);gap:8px}} input,select{{width:100%;border:1px solid var(--line);border-radius:10px;padding:10px;background:#fff;color:var(--ink)}} .chips{{display:flex;gap:7px;overflow:auto;margin-top:9px}} .chip{{border:1px solid var(--line);border-radius:999px;background:#fff;padding:7px 10px;white-space:nowrap;font-size:12px}} .chip.active{{background:var(--soft);border-color:#9dcedf;color:#075a75;font-weight:700}}
.resulthead{{display:flex;justify-content:space-between;align-items:end;margin:10px 2px}} .resulthead b{{font-size:15px}} .hint{{font-size:11px;color:var(--muted)}} .cards{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}} .card{{background:#fff;border:1px solid var(--line);border-radius:16px;padding:13px;box-shadow:var(--shadow)}} .row{{display:flex;align-items:center;gap:8px;flex-wrap:wrap}} .merchant{{font-weight:800;color:#0b5a98}} .pill{{font-size:11px;border:1px solid var(--line);border-radius:999px;padding:3px 7px;color:var(--muted)}} .title{{font-size:16px;font-weight:800;margin:8px 0 4px;line-height:1.35}} .price{{display:flex;align-items:baseline;gap:8px;margin:10px 0}} .promo{{font-size:24px;font-weight:900;color:var(--teal)}} .regular{{color:var(--muted);text-decoration:line-through}} .discount{{font-weight:800;color:var(--bad)}} .meta{{font-size:12px;color:#4d6174;line-height:1.65}} .badges{{display:flex;gap:5px;flex-wrap:wrap;margin-top:9px}} .badge{{font-size:10px;padding:4px 7px;border-radius:999px;background:#eef3f6;color:#516474}} .badge.good{{background:#e5f6ee;color:var(--good)}} .badge.warn{{background:#fff2d8;color:var(--warn)}} .badge.info{{background:#e7f4fb;color:#086c8c}} details{{margin-top:9px;border-top:1px dashed var(--line);padding-top:8px}} summary{{font-size:12px;font-weight:700;color:var(--blue)}} .detail{{font-size:11px;line-height:1.6;color:#52677a;margin-top:8px;overflow-wrap:anywhere}} .sourcebtn{{display:inline-block;margin-top:6px}}
.placecard .title{{margin-bottom:8px}} .semantics{{border-left:4px solid #e7a530;background:#fff8e9;padding:10px 12px;border-radius:10px;margin-bottom:12px;font-size:12px;line-height:1.55}} .systembox{{background:#fff;border:1px solid var(--line);border-radius:16px;padding:14px;box-shadow:var(--shadow)}} .kv{{display:grid;grid-template-columns:180px 1fr;gap:7px 12px;font-size:12px;margin:8px 0}} .kv div:nth-child(odd){{color:var(--muted)}} .json{{white-space:pre-wrap;background:#f6f9fb;border-radius:12px;padding:10px;font-size:10px;overflow:auto;max-height:300px}} .empty{{grid-column:1/-1;text-align:center;padding:35px;color:var(--muted)}} .more{{display:none;width:100%;margin:12px 0;border:1px solid var(--line);border-radius:12px;background:#fff;padding:11px;color:var(--blue);font-weight:700}}
@media(max-width:760px){{.stats{{grid-template-columns:repeat(2,1fr)}}.grid2{{grid-template-columns:1fr 1fr}}.grid2 .wide{{grid-column:1/-1}}.cards{{grid-template-columns:1fr}}.kv{{grid-template-columns:1fr}}}}
</style></head><body><div class="shell"><header class="hero"><div class="top"><div class="logo">🏷️</div><div><h1>Promo Intelligence Lab</h1><div class="sub">หน้าทดลอง · Published Read Model · Read-only</div></div><div class="testbadge">TEST</div></div><div class="notice">หน้านี้แยกจากหน้าบ้านหลักและไม่เขียนข้อมูลกลับระบบ · ข้อมูลสาขาใน Place Directory หมายถึง “สาขามีอยู่จริง” เท่านั้น ไม่ได้แปลว่าโปรโมชั่นทุกตัวใช้ได้ทุกสาขา</div></header>
<div class="stats" id="stats"></div><nav class="tabs"><button class="tab active" data-tab="offers">โปรโมชั่น</button><button class="tab" data-tab="places">สถานที่ / สาขา</button><button class="tab" data-tab="system">สถานะระบบ</button></nav>
<section class="panel active" id="panel-offers"><div class="controls"><div class="grid2"><input class="wide" id="oq" placeholder="ค้นหาสินค้า ร้าน แบรนด์ จังหวัด สาขา..."><select id="omerchant"><option value="">ทุกร้าน</option></select><select id="otype"><option value="">ทุกประเภท</option></select><select id="ochannel"><option value="">ทุกช่องทาง</option><option value="online">ออนไลน์</option><option value="store">หน้าร้าน</option><option value="omnichannel">ออนไลน์ + หน้าร้าน</option><option value="unknown">ไม่ระบุ</option></select><select id="osort"><option value="discount">ส่วนลดมาก</option><option value="price">ราคาโปรต่ำ</option><option value="expiry">ใกล้หมดโปร</option><option value="merchant">ร้าน A-Z</option></select></div><div class="chips" id="ochips"><button class="chip active" data-q="all">ทั้งหมด</button><button class="chip" data-q="active">ยัง Active</button><button class="chip" data-q="nationwide">ทั่วประเทศ</button><button class="chip" data-q="online">ออนไลน์</button><button class="chip" data-q="directbranch">มีสาขาอ้างอิงตรง</button><button class="chip" data-q="verified">Verified</button></div></div><div class="resulthead"><b id="offerCount"></b><span class="hint" id="offerHint"></span></div><div class="cards" id="offerCards"></div><button class="more" id="offerMore">แสดงเพิ่ม</button></section>
<section class="panel" id="panel-places"><div class="semantics">Place Directory ใช้ค้นหาว่า merchant มีสาขาใดบ้าง และที่ไหน แต่การนำ Offer ไปใช้กับสาขาต้องตรวจ <b>applicability/channel</b> ของ Offer แยกอีกครั้ง</div><div class="controls"><div class="grid2"><input class="wide" id="pq" placeholder="ค้นหาร้าน สาขา จังหวัด อำเภอ ที่อยู่..."><select id="pmerchant"><option value="">ทุกร้าน</option></select><select id="pkind"><option value="">Merchant + Branch</option><option value="branch">เฉพาะสาขา</option><option value="merchant">เฉพาะ Merchant</option></select><select id="pprov"><option value="">ทุกจังหวัด</option></select><select id="pprec"><option value="">ทุก precision</option></select></div></div><div class="resulthead"><b id="placeCount"></b><span class="hint" id="placeHint"></span></div><div class="cards" id="placeCards"></div><button class="more" id="placeMore">แสดงเพิ่ม</button></section>
<section class="panel" id="panel-system"><div class="systembox"><h3 style="margin-top:0">Published Snapshot</h3><div class="kv" id="syskv"></div><div class="semantics" style="margin-top:14px">Consumer contract: Read-only · Published offers เป็น verified/partial ที่ไม่ expired/stale · Branch directory ไม่ใช่ offer applicability</div><details><summary>ดู Manifest JSON</summary><pre class="json" id="manifestJson"></pre></details></div></section></div>
<script>
const PAYLOAD='{payload}'; const D=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(PAYLOAD),c=>c.charCodeAt(0)))); const M=D.manifest||{{}}, O=D.offers||[], P=D.places||[], I=D.index||{{merchant_branches:{{}}}};
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c])); const fmt=n=>new Intl.NumberFormat('th-TH').format(n||0); const val=(o,k)=>o&&o[k]!=null?o[k]:'';
function money(x){{return x==null?'-':new Intl.NumberFormat('th-TH',{{style:'currency',currency:'THB',maximumFractionDigits:2}}).format(x)}} function app(o){{return o.applicability||{{}}}} function ver(o){{return o.verification||{{}}}} function geo(o){{return o.geography||{{locations:[]}}}} function price(o){{return o.pricing||{{}}}}
function branchCount(o){{const id=o.merchant_place_ref; return id&&I.merchant_branches&&I.merchant_branches[id]?I.merchant_branches[id].length:0}} function offerText(o){{return JSON.stringify([o.merchant,o.item,o.conditions,o.applicability,o.geography]).toLowerCase()}} function placeText(p){{return JSON.stringify([p.merchant,p.branch,p.location,p.search_terms]).toLowerCase()}}
function merchants(){{return [...new Set(O.map(o=>val(o.merchant,'name')).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'th'))}} function placeMerchants(){{return [...new Set(P.map(p=>val(p.merchant,'name')).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'th'))}}
function fillSelect(id,vals){{$(id).innerHTML += vals.map(x=>`<option value="${{esc(x)}}">${{esc(x)}}</option>`).join('')}} fillSelect('omerchant',merchants()); fillSelect('pmerchant',placeMerchants()); fillSelect('otype',[...new Set(O.map(o=>o.offer_type).filter(Boolean))].sort()); fillSelect('pprov',[...new Set(P.map(p=>val(p.location,'province_raw')||val(p.location,'province')).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'th'))); fillSelect('pprec',[...new Set(P.map(p=>p.precision).filter(Boolean))].sort());
const st={{oq:'all',olim:80,plim:80}};
function offerOk(o){{const q=$('oq').value.trim().toLowerCase(); if(q&&!offerText(o).includes(q))return false; if($('omerchant').value!==''&&val(o.merchant,'name')!==$('omerchant').value)return false; if($('otype').value!==''&&o.offer_type!==$('otype').value)return false; if($('ochannel').value!==''&&app(o).channel!==$('ochannel').value)return false; const a=app(o),v=ver(o); if(st.oq==='active'&&v.expiry_state!=='active')return false; if(st.oq==='nationwide'&&a.scope!=='nationwide')return false; if(st.oq==='online'&&a.channel!=='online')return false; if(st.oq==='directbranch'&&!(o.place_refs||[]).length)return false; if(st.oq==='verified'&&v.verification_state!=='verified')return false; return true}}
function offerSort(a,b){{const s=$('osort').value; if(s==='price')return (price(a).promo_price??1e99)-(price(b).promo_price??1e99); if(s==='expiry')return String(val(a.validity,'end')||'9999').localeCompare(String(val(b.validity,'end')||'9999')); if(s==='merchant')return String(val(a.merchant,'name')).localeCompare(String(val(b.merchant,'name')),'th'); return (Number(price(b).discount_percent)||-1)-(Number(price(a).discount_percent)||-1)}}
function offerCard(o){{const p=price(o),a=app(o),v=ver(o),bc=branchCount(o),direct=(o.place_refs||[]).length; const promo=p.promo_price!=null?`<span class="promo">${{money(p.promo_price)}}</span>${{p.regular_price!=null?`<span class="regular">${{money(p.regular_price)}}</span>`:''}}${{p.discount_percent!=null?`<span class="discount">-${{Number(p.discount_percent).toFixed(0)}}%</span>`:''}}`:`<span>${{esc(o.offer_type||'โปรโมชั่น')}}</span>`; return `<article class="card"><div class="row"><span class="merchant">${{esc(val(o.merchant,'name')||'-')}}</span><span class="pill">${{esc(o.offer_type||'promo')}}</span></div><div class="title">${{esc(val(o.item,'name')||'โปรโมชั่น')}}</div><div class="price">${{promo}}</div><div class="meta">📅 ${{esc(val(o.validity,'start')||'-')}} – ${{esc(val(o.validity,'end')||'-')}}<br>📍 scope=${{esc(a.scope||'unknown')}} · channel=${{esc(a.channel||'unknown')}}<br>🏬 Place Directory ของ merchant นี้: ${{bc}} สาขา · direct offer refs: ${{direct}}</div><div class="badges"><span class="badge ${{v.verification_state==='verified'?'good':'warn'}}">${{esc(v.verification_state||'unknown')}}</span><span class="badge ${{p.verification_state==='verified'?'good':'warn'}}">price ${{esc(p.verification_state||'unknown')}}</span>${{a.scope==='nationwide'?'<span class="badge info">nationwide</span>':''}}${{direct?'<span class="badge good">direct branch evidence</span>':''}}</div><details><summary>หลักฐาน / Contract</summary><div class="detail">Offer ID: ${{esc(o.offer_id||'-')}}<br>Merchant place ref: ${{esc(o.merchant_place_ref||'-')}}<br>Place refs: ${{esc((o.place_refs||[]).join(', ')||'-')}}<br>Price integrity: ${{esc(p.verification_state||'unknown')}} · anomalies=${{esc((p.anomalies||[]).join(', ')||'-')}}<br>Conditions: ${{esc((o.conditions||[]).join(' · ')||'-')}}<br>Evidence: ${{esc(val(o.evidence,'extracted_text')||'-')}}${{val(o.source,'url')?`<br><a class="sourcebtn" href="${{esc(val(o.source,'url'))}}" target="_blank" rel="noopener">เปิด source ↗</a>`:''}}</div></details></article>`}}
function renderOffers(){{let a=O.filter(offerOk).sort(offerSort),s=a.slice(0,st.olim); $('offerCount').textContent=`พบ ${{fmt(a.length)}} โปรโมชั่น`; $('offerHint').textContent=a.length>s.length?`แสดง ${{fmt(s.length)}} รายการแรก`:''; $('offerCards').innerHTML=s.length?s.map(offerCard).join(''):'<div class="empty">ไม่พบข้อมูล</div>'; $('offerMore').style.display=a.length>s.length?'block':'none'}}
function placeOk(p){{const q=$('pq').value.trim().toLowerCase(); if(q&&!placeText(p).includes(q))return false; if($('pmerchant').value&&val(p.merchant,'name')!==$('pmerchant').value)return false; if($('pkind').value&&p.record_kind!==$('pkind').value)return false; const prov=val(p.location,'province_raw')||val(p.location,'province'); if($('pprov').value&&prov!==$('pprov').value)return false; if($('pprec').value&&p.precision!==$('pprec').value)return false; return true}}
function placeCard(p){{const l=p.location||{{}},b=p.branch||{{}},v=p.verification||{{}}; const bc=p.record_kind==='merchant'&&I.merchant_branches&&I.merchant_branches[p.place_id]?I.merchant_branches[p.place_id].length:0; return `<article class="card placecard"><div class="row"><span class="merchant">${{esc(val(p.merchant,'name')||'-')}}</span><span class="pill">${{esc(p.record_kind||'-')}}</span></div><div class="title">${{esc(b.name||val(p.merchant,'name')||p.place_id)}}</div><div class="meta">📍 ${{esc([l.subdistrict,l.district,l.province_raw||l.province].filter(Boolean).join(' · ')||'ยังไม่มี structured location')}}<br>${{l.address?`🏠 ${{esc(l.address)}}<br>`:''}}Precision: ${{esc(p.precision||'unknown')}}${{p.record_kind==='merchant'?` · branches in directory: ${{bc}}`:''}}</div><div class="badges"><span class="badge ${{v.verification_state==='verified'?'good':'warn'}}">${{esc(v.verification_state||'unknown')}}</span>${{l.postal_code?'<span class="badge info">postal</span>':''}}${{l.latitude!=null&&l.longitude!=null?'<span class="badge good">coordinates</span>':''}}</div><details><summary>Place evidence</summary><div class="detail">Place ID: ${{esc(p.place_id)}}<br>Parent: ${{esc(p.parent_place_id||'-')}}<br>Search terms: ${{esc((p.search_terms||[]).join(' · '))}}<br>Evidence records: ${{(p.evidence||[]).length}}</div></details></article>`}}
function renderPlaces(){{let a=P.filter(placeOk),s=a.slice(0,st.plim); $('placeCount').textContent=`พบ ${{fmt(a.length)}} สถานที่`; $('placeHint').textContent=a.length>s.length?`แสดง ${{fmt(s.length)}} รายการแรก`:''; $('placeCards').innerHTML=s.length?s.map(placeCard).join(''):'<div class="empty">ไม่พบข้อมูล</div>'; $('placeMore').style.display=a.length>s.length?'block':'none'}}
function renderStats(){{const branches=P.filter(p=>p.record_kind==='branch').length,merchants=P.filter(p=>p.record_kind==='merchant').length; $('stats').innerHTML=[[O.length,'Published Offers'],[P.length,'Published Places'],[branches,'Physical Branches'],[Object.keys(I.merchant_branches||{{}}).length,'Merchants with Branches']].map(([n,l])=>`<div class="stat"><b>${{fmt(n)}}</b><span>${{l}}</span></div>`).join('')}}
function renderSystem(){{const kv=[['Publication ID',M.publication_id],['Published at',M.published_at],['Offer contract',M.offer_contract],['Place contract',M.place_contract],['Offer count',M.offer_count],['Place count',M.place_count],['Branch place count',M.branch_place_count],['Branch-index merchants',M.merchant_branch_index_count],['Read-only',val(M.policy,'read_only')],['Branch ≠ applicability',val(M.policy,'branch_directory_not_offer_applicability')]]; $('syskv').innerHTML=kv.map(([k,v])=>`<div>${{esc(k)}}</div><div><b>${{esc(v)}}</b></div>`).join(''); $('manifestJson').textContent=JSON.stringify(M,null,2)}}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id==='panel-'+b.dataset.tab))}}); ['oq','omerchant','otype','ochannel','osort'].forEach(id=>$(id).addEventListener(id==='oq'?'input':'change',()=>{{st.olim=80;renderOffers()}})); $('ochips').onclick=e=>{{const b=e.target.closest('[data-q]');if(!b)return;st.oq=b.dataset.q;st.olim=80;document.querySelectorAll('#ochips .chip').forEach(x=>x.classList.toggle('active',x===b));renderOffers()}}; $('offerMore').onclick=()=>{{st.olim+=80;renderOffers()}}; ['pq','pmerchant','pkind','pprov','pprec'].forEach(id=>$(id).addEventListener(id==='pq'?'input':'change',()=>{{st.plim=80;renderPlaces()}})); $('placeMore').onclick=()=>{{st.plim+=80;renderPlaces()}};
renderStats();renderSystem();renderOffers();renderPlaces();
</script></body></html>'''

def main()->int:
    ap=argparse.ArgumentParser(description='Build separate read-only Promo Intelligence Lab frontend from Published Read Model')
    ap.add_argument('--published-dir',type=Path,default=PUB)
    ap.add_argument('--output',type=Path,default=DEFAULT_OUTPUT)
    a=ap.parse_args(); pd=a.published_dir if a.published_dir.is_absolute() else ROOT/a.published_dir; out=a.output if a.output.is_absolute() else ROOT/a.output
    m=load_json(pd/'manifest.json'); offers=load_jsonl(pd/'promo_offer_v1.jsonl'); places=load_jsonl(pd/'promo_place_v1.jsonl'); idx=load_json(pd/'merchant_branch_index_v1.json')
    # Basic consistency gate so the Lab cannot silently present a partial snapshot.
    if int(m.get('offer_count',-1))!=len(offers): raise SystemExit(f'MANIFEST_OFFER_COUNT_MISMATCH manifest={m.get("offer_count")} actual={len(offers)}')
    if int(m.get('place_count',-1))!=len(places): raise SystemExit(f'MANIFEST_PLACE_COUNT_MISMATCH manifest={m.get("place_count")} actual={len(places)}')
    out.write_text(build_html(m,offers,places,idx),encoding='utf-8')
    print('PROMO_LAB_BUILD=PASS'); print(f'PUBLICATION_ID={m.get("publication_id","-")}'); print(f'OFFERS_EMBEDDED={len(offers)}'); print(f'PLACES_EMBEDDED={len(places)}'); print(f'BRANCHES_EMBEDDED={sum(p.get("record_kind")=="branch" for p in places)}'); print(f'MERCHANTS_WITH_BRANCHES={len((idx.get("merchant_branches") or {}))}'); print('PROMO_LAB_MODE=READ_ONLY_PUBLISHED_SNAPSHOT'); print(f'OUTPUT={out}')
    return 0
if __name__=='__main__': raise SystemExit(main())
